### ISSUE TITLE
PushBullet API not working

### ISSUE THREAD

**Issue by bushcraftbuddy** [kjdElectronics/fd-tone-notify#25]
I am attempting to set all this up but for some reason it does not like my API key from pushbullet. I don't know if I am missing something with the configuration (I probably am) but if someone could take a look at my configs and see anything wrong that would be awesome. I added the API key into the secrets.json but it doesn't seem to care that it's in there

![Screenshot 2024-05-12 223620](https://github.com/kjdElectronics/fd-tone-notify/assets/115857828/e454ffc4-9fb7-4fa4-8394-10ef1f40a535)
[default.json](https://github.com/kjdElectronics/fd-tone-notify/files/15289132/default.json)
[secrets.json](https://github.com/kjdElectronics/fd-tone-notify/files/15289133/secrets.json)

(My api key is not completely in the configs but everything else is exactly the same)

**Comment by kdolan** [comment]
Can you start with the --silly option? That will show more logs. Also please run test notifications

**Comment by bushcraftbuddy** [comment]
Here's with --silly and --test-notifications

![image](https://github.com/kjdElectronics/fd-tone-notify/assets/115857828/1ec2b6c8-1b25-4c6d-83a5-4415ca90afd6)

**Comment by kdolan** [comment]
This is the second issue with Pushbullet in a short period of time. If you try to send a notification directly via the API using postman does that work?

**Comment by bushcraftbuddy** [comment]
Yes it does

![image](https://github.com/kjdElectronics/fd-tone-notify/assets/115857828/dd4df8cd-660f-4c08-aa3b-33c5a328c15d)

**Comment by bushcraftbuddy** [comment]
I believe the issue is that FD-Tone is using "https://api.pushbullet.com/v2" without the added "pushes" to the end. without that my postman request failed

**Comment by kdolan** [comment]
I will further investigate this. The version of FD Tone Notify I've been using has continued to send pushes without issue so I'm not sure what the outstanding variable is.
I will try and figure out what it going on

**Comment by bushcraftbuddy** [comment]
okay I will keep messing with the API and see if I can recreate the same errors.

**Comment by kdolan** [comment]
@bushcraftbuddy I have pushed an update to main. Can you trying running from source to see if this resolves the issue? It looks like the API key was not correctly being picked up from the secrets file.

**Comment by bushcraftbuddy** [comment]
I get this error when running from source. I just have to run "node index.js" in the fd-tone-notify-main directory correct? 

![image](https://github.com/kjdElectronics/fd-tone-notify/assets/115857828/92a65153-f2c0-4f4b-951f-bbb3eacf7bdd)

**Comment by kdolan** [comment]
Make sure you run npm install
Then yes. if you run `node index.js --silly` you will get all the logging.

**Comment by bushcraftbuddy** [comment]
that works! I'll have to push the updated mains to my trunking server, but it does work now. thank you for fixing it so quickly!

**Comment by kdolan** [comment]
Quickly is relative... This bug has evidently been in there for a LONG time. I use a .env file to pass secrets which would have bypassed this issue. 
Thank you to @bushcraftbuddy and @mattfox27 for both reporting this issue.

**Comment by MrJordanRoth** [comment]
Not sure if this would require a reopening, but this is the same issue on the Windows .exe file

**Comment by kdolan** [comment]
@MrJordanRoth There has not been a new Release Build since this bug was fixed. You can use a .env file to circumvent the issue as described above. You can also either run from source or do a build from source.

**Comment by MrJordanRoth** [comment]
OK, I will look to see how to use the .env in the Windows environment.

**Comment by mattfox27** [comment]
i made a variables.env file and copied the values from secrets.json and still get the same error for pushbullet, are you supposed to something diffrent?

**Comment by kdolan** [comment]
It is simply".env"
